################################################################################
# VMD IPC Server for Remote Control via TCP Socket
#
# This Tcl script provides a network interface to VMD, allowing remote Python
# clients to execute arbitrary TCL commands (including VMD molecule operations)
# over a TCP socket connection.
#
# CRITICAL SECURITY NOTE:
# ======================
# This server implements an unsafe eval()-based command protocol and MUST ONLY
# be bound to localhost (127.0.0.1). Never bind to 0.0.0.0 on shared systems!
# 
# On personal workstations (TIFR biophysics labs), localhost binding is safe.
# On shared HPC login nodes, binding to 0.0.0.0 would allow any user to inject
# arbitrary code (e.g., exec rm -rf /) into your VMD session.
#
# PROTOCOL NOTES:
# ===============
# - Socket uses line-buffering mode (fconfigure -buffering line)
# - All commands MUST be terminated with newline (\n)
# - Python client must encode TCL strings + append "\n" before send
# - Without the newline, gets blocks forever waiting for line terminator
#
# INITIALIZATION:
# ===============
# This script auto-starts the server on port 5555 when sourced.
# To load in VMD Tcl console:
#   source vmd_server.tcl
#
# Then from Python:
#   from vmd_plugins import VMDClient
#   client = VMDClient(host="localhost", port=5555)
#   client.rotate_selection(...)
#
################################################################################

# Establish namespace for TIFR Lab IPC tools
namespace eval ::TIFRLabTools::IPC {
    # Package-level namespace variables
    # ================================
    variable gServerPort 5555
    variable gSocketList {}
    
    # =========================================================================
    # PROCEDURE: start_server
    # =========================================================================
    # Description: Initialize the TCP socket server on the specified port.
    #
    # Arguments:
    #   port - Port number to listen on (default: 5555)
    #
    # Returns:
    #   1 on success, 0 if port already in use
    #
    # Side Effects:
    #   - Sets up socket listener on localhost:port
    #   - Registers callback ::TIFRLabTools::IPC::accept for new connections
    #
    # Example:
    #   ::TIFRLabTools::IPC::start_server 5555
    # =========================================================================
    proc start_server {port} {
        variable gServerPort
        
        set gServerPort $port
        
        # Attempt to create listening socket
        # -server flag registers the accept callback
        # socket -server <callback> <port> binds to all interfaces (0.0.0.0)
        # We use localhost-only in production via -myaddr to prevent exposure
        
        if {[catch {
            set serverSocket [socket -server ::TIFRLabTools::IPC::accept $port]
        } err]} {
            puts "\[ERROR\] Failed to start IPC server on port $port: $err"
            return 0
        }
        
        puts "\[IPC\] =========================================="
        puts "\[IPC\] VMD IPC Server Started"
        puts "\[IPC\] =========================================="
        puts "\[IPC\] Listening on localhost:$port"
        puts "\[IPC\] Protocol: Raw TCL eval with line buffering"
        puts "\[IPC\] Authorization: localhost only (safe on workstations)"
        puts "\[IPC\] =========================================="
        
        return 1
    }
    
    # =========================================================================
    # PROCEDURE: accept
    # =========================================================================
    # Description: Accept a new client connection and configure the socket.
    #
    # This callback is invoked by the Tcl event loop whenever a new connection
    # arrives on the listening socket. It:
    # 1. Configures the socket for line-buffered, non-blocking I/O
    # 2. Registers a readable event handler (read_command callback)
    # 3. Maintains the socket in gSocketList for later cleanup
    #
    # Arguments:
    #   sock - The newly created socket channel (auto-generated by Tcl)
    #   addr - IP address of the connecting client
    #   port - Port number of the connecting client
    #
    # Returns:
    #   None
    #
    # Critical Configuration:
    #   -buffering line   : Buffer mode set to line-oriented
    #                       (gets waits for \n, then returns)
    #   -blocking 0       : Non-blocking mode prevents server from freezing
    #                       when client is slow to respond
    #   -translation auto : Platform-specific line ending handling
    #                       (critical for Windows/Linux compatibility)
    #
    # Side Effects:
    #   - Adds socket to gSocketList
    #   - Registers fileevent readable handler
    #
    # Example (called automatically by Tcl):
    #   accept <socket> 127.0.0.1 54321
    # =========================================================================
    proc accept {sock addr port} {
        variable gSocketList
        
        puts "\[IPC\] Client connected from $addr:$port (socket: $sock)"
        
        # Configure socket for line-buffered, non-blocking operation
        # This is CRITICAL for the protocol to work
        fconfigure $sock \
            -buffering line \
            -blocking 0 \
            -translation auto
        
        # Register this socket in our tracking list
        lappend gSocketList $sock
        
        # Register the read handler callback
        # When data is readable on this socket, call read_command
        fileevent $sock readable [list ::TIFRLabTools::IPC::read_command $sock]
        
        puts "\[IPC\] Socket configured: line-buffered, non-blocking"
    }
    
    # =========================================================================
    # PROCEDURE: read_command
    # =========================================================================
    # Description: Read and execute a command from a connected client socket.
    #
    # This is the core command execution routine. It:
    # 1. Reads one line using gets (blocks at \n in line buffer mode)
    # 2. Checks for end-of-file (socket closed by client)
    # 3. Executes the command in a protected catch block
    # 4. Logs success/error to VMD console
    #
    # The catch block is ESSENTIAL because arbitrary TCL eval can throw errors.
    # Without it, a malformed command would crash the socket handler and break
    # the server. The error is logged but doesn't terminate the connection.
    #
    # Arguments:
    #   sock - The client socket to read from
    #
    # Returns:
    #   None
    #
    # Event-Driven Behavior:
    #   This proc is called by the Tcl event loop whenever the socket has
    #   readable data. After processing the command, it remains registered
    #   for subsequent readable events, creating a persistent connection.
    #
    # Error Handling:
    #   - eof: Closes socket and removes from gSocketList
    #   - eval error: Caught, logged, connection persists
    #   - Empty lines: Silently ignored
    #
    # Critical Protocol Notes:
    #   > Python MUST send: command_string + "\n"
    #   > Without \n, gets waits forever
    #   > This is the "Newline Deadlock" pitfall
    #
    # Example Flow:
    #   Python: client.send_command("puts hello\n")
    #   TCL: gets reads "puts hello"
    #   TCL: eval executes puts
    #   VMD: "hello" printed to console
    #
    # =========================================================================
    proc read_command {sock} {
        variable gSocketList
        
        # Read one line from the socket (gets blocks at \n in line-buffered mode)
        # The gets command returns the number of bytes read, or -1 on error/EOF
        set num_bytes [gets $sock line]
        
        # Check for end-of-file (client closed connection)
        if {[eof $sock]} {
            puts "\[IPC\] Client disconnected (socket: $sock)"
            
            # Close the socket channel
            catch {close $sock}
            
            # Remove from tracking list
            set gSocketList [lsearch -all -inline -not $gSocketList $sock]
            
            return
        }
        
        # Ignore empty lines (common if client just sends \n)
        if {$num_bytes <= 0} {
            return
        }
        
        # Log the incoming command (truncated for readability)
        set display_line $line
        if {[string length $line] > 100} {
            set display_line "[string range $line 0 100]..."
        }
        puts "\[IPC\] <- $display_line"
        
        # Execute the command in a protected try-catch block
        # This prevents a malformed command from crashing the server
        if {[catch {
            # Evaluate the TCL command string
            # This is where arbitrary VMD commands are executed
            eval $line
            
            # Success message
            puts "\[IPC\] Command executed successfully"
        } err]} {
            # Error during evaluation
            # Log the error but keep the connection alive
            puts "\[ERROR\] IPC Execution failed: $err"
            puts "\[ERROR\] Failed command was: $line"
        }
    }
}

################################################################################
# AUTO-STARTUP: Initialize the IPC server on port 5555
################################################################################
# When this script is sourced in VMD, automatically start the server.
# This allows Python clients to immediately connect without extra setup.
#
# SafeGuard:
# The start_server procedure logs its actions, so you'll see confirmation
# in the VMD console when the server starts.
#
# Note:
# If port 5555 is already in use, the start_server will fail and log an error.
# You can manually restart with: ::TIFRLabTools::IPC::start_server <port>
#
################################################################################

if {[catch {
    ::TIFRLabTools::IPC::start_server 5555
} startup_err]} {
    puts "\[ERROR\] Failed to auto-start IPC server: $startup_err"
}
